### ISSUE TITLE
Unable to change binary addresses via linker script

### ISSUE THREAD

**Issue by baltazarortiz** [ucb-bar/libgloss-htif#4]
Running into the same issue as described by Tim [in the chipyard group](https://groups.google.com/forum/#!topic/chipyard/yBUkT6NG5AY) - Changing the starting address in the linker script from `
. = 0x80000000` to something else seems to be ignored even though as far as I can tell, the specs command is being passed into the GCC commands. Manually pointing to the linker script with `-T` also doesn't work.

**Comment by baltazarortiz** [comment]
I'm able to replicate this with the `make check` output as well as the tests in the Chipyard test repo, in case that's an easier minimal case to look at.

**Comment by a0u** [comment]
496a0b66b644241f1062e7c4ade87c55fa2fd286 allows `-T` to override `htif.ld`.

**Comment by baltazarortiz** [comment]
Thank you!
